# config de endpoint info para spring actuator
info:
  app:
    name: ${project.name}
    description: Api para proveer servicios a M&A
    version: ${project.version}
# config de endpoints para spring actuator
springdoc:
  swagger-ui:
    path: /swagger-ui.html
management:
  endpoints:
    enabled: false
  health:
    enabled: true
  server:
    address: 0.0.0.0
    port: 8019
  endpoint:
    restart:
      enabled: true
logging:
  config: classpath:logback-spring.xml
# config de endpoints para spring actuator
server:
  ssl:
    enabled: true
    key-store: classpath:keystore/santanderconsumer.p12
    key-store-password: Colombia2020*
    key-store-type: pkcs12
    key-alias: santanderconsumer.co
    key-password: Colombia2020*
  port: 8019
spring:
  profiles:
    active: "@spring.profiles.active@"
  cloud:
    kubernetes:
      # define politica para el servicio cuando se hacen cambios en el configmap
      reload:
        enabled: true
keycloak:
  realm: sc-security
  auth-server-url: https://sso-security.santanderconsumer.co:8443/auth
  ssl-required: external
  resource: cli-pionner-security
  security-constraints:
  - security-collections:
    - patterns:
      - /pionner
    auth-roles:
    - uma_authorization
spring.main.allow-bean-definition-overriding: true


