# config de endpoint info para spring actuator
info:
  app:
    name: ${project.name}
    description: Api para proveer servicios de M&A
    version: ${project.version}
# config de endpoints para spring actuator
management:
  endpoints:
    enabled: false
  health:
    enabled: true
  server:
    address: 0.0.0.0
    port: 8017
  endpoint:
    restart:
      enabled: true
logging:
  config: classpath:logback-spring.xml
# config de endpoints para spring actuator
server:
  ssl:
    enabled: true
    key-store: classpath:keystore/santanderconsumer.p12
    key-store-password: Colombia2020*
    key-store-type: pkcs12
    key-alias: santanderconsumer.co
    key-password: Colombia2020*
  port: 8017
spring:
  profiles:
    active: "@spring.profiles.active@"
  cloud:
    kubernetes:
      # define politica para el servicio cuando se hacen cambios en el configmap
      reload:
        enabled: true
  datasource: 
    platform: postgresql
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/Piezas
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true        
keycloak:
  realm: sc-security
  auth-server-url: https://sso-security.santanderconsumer.co:8443/auth
  ssl-required: external
  resource: cli-m&a-security
  security-constraints:
  - security-collections:
    - patterns:
      - /*
    auth-roles:
    - uma_authorization
spring.main.allow-bean-definition-overriding: true
